version: '3'

services:
  auth:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-wobgob}
      MYSQL_DATABASE: auth
    volumes:
      - auth:/var/lib/mysql
  characters:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-wobgob}
      MYSQL_DATABASE: auth
    volumes:
      - characters:/var/lib/mysql
  world:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-wobgob}
      MYSQL_DATABASE: world
    volumes:
      - world:/var/lib/mysql
  server:
    image: wobgob/core:latest
    depends_on:
      - auth
      - characters
      - world
    tty: true
    stdin_open: true
    ports:
      - '3724:3724'
      - '8085:8085'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-wobgob}
      ADDRESS: ${ADDRESS}
    volumes:
      - bin:/usr/bin
      - etc:/usr/etc
      - log:/var/log
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  auth:
  characters:
  world:
  bin:
  etc:
  log:
